// Code generated by by github.com/pfcm/fxp/fix/gen DO NOT EDIT.

package fix

import (
	"fmt"
	"math/rand"
	"testing"
)

func TestU17FloatRoundTrip(t *testing.T) {
	for i := 0; i < 256; i++ {
		u := U17(i)
		f := U17ToFloat[float64](u)
		u2 := U17FromFloat(f)
		if u != u2 {
			t.Errorf("FromFloat(ToFloat(%x)) = %x", u, u2)
		}
	}
}

// TODO: there's probably more things to test
